services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: learn_base
      POSTGRES_MULTIPLE_DATABASES: "learn_base,kakoy_kaif"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - data-eng-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 30s
      timeout: 10s
      retries: 3

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    container_name: jupyter-lab
    environment:
      JUPYTER_TOKEN: "dataengineer"
      CHOWN_HOME: "yes"
      CHOWN_HOME_OPTS: "-R"
    volumes:
      - ./jupyter:/home/jovyan
    ports:
      - "8888:8888"
    networks:
      - data-eng-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8888/api || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  superset:
    image: amancevice/superset:latest
    container_name: superset
    environment:
      SUPERSET_SECRET_KEY: 'my-super-secret-key-for-learning'
      SUPERSET_DB_HOST: postgres-db
      SUPERSET_DB_PORT: 5432
      SUPERSET_DB_USER: admin
      SUPERSET_DB_PASSWORD: admin
      SUPERSET_DB_NAME: superset
      SUPERSET_LOAD_EXAMPLES: 'yes'
    volumes:
      - ./superset/data:/var/lib/superset
    ports:
      - "8088:8088"
    depends_on:
      - postgres-db
    networks:
      - data-eng-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8088/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s

volumes:
  postgres_data:

networks:
  data-eng-net:
    driver: bridge